interface ReportFooterProps {
  pageCount: number
}

export default function ReportFooter({ pageCount }: ReportFooterProps) {
  return (
    <>
      <p className="footer-note">
        Generated by Soroban Guard · Veritas Vaults Network
      </p>
      <div className="page-number">Page <span className="page-num">1</span> of {pageCount}</div>
    </>
  )
}
